name: CI

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: ruff check
        uses: chartboost/ruff-action@v1
        with:
          version: 0.1.9
      - name: ruff format
        uses: chartboost/ruff-action@v1
        with:
          version: 0.1.9
          args: format --check
